stages:
- integration-tests
- e2e
- release

integration-tests:
  image: node:13-stretch
  stage: integration-tests
  only:
    - master
    - dev
    - merge_requests
  before_script:
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then export HANA3D_ENV=production; else if [ "$CI_COMMIT_BRANCH" == "dev" ]; then export HANA3D_ENV=dev; else export HANA3D_ENV=dev; fi; fi;
    - export DEBIAN_FRONTEND=noninteractive
    - apt -q update && apt install --no-install-recommends -y -q libglu1-mesa libxi6 libpcre3 zip
    - BLENDER_URL=https://download.blender.org/release/Blender2.90/blender-2.90.0-linux64.tar.xz
    - BLENDER_VERSION=$(echo $BLENDER_URL | grep -Po 'blender-2\.\K[0-9]+')
    - echo "Installing Blender 2.${BLENDER_VERSION}"
    - mkdir /opt/blender
    - echo "Downloading from $BLENDER_URL"
    - curl -SL "$BLENDER_URL" | tar -Jx -C /opt/blender --strip-components=1
    - ln -s /opt/blender/blender /usr/local/bin/blender
    - PATH="/opt/blender/blender:${PATH}"
    - ln -s /lib64/libpcre.so.3 /lib64/libpcre.so.1
  script:
    - BLENDER_SCRIPTS_PATH=/opt/blender/2.90/scripts STAGE=$HANA3D_ENV make clean build install
    - make test

e2e:
  stage: e2e
  only:
    - dev
    - master
  script:
    - "curl -X POST -F token=$E2E_TOKEN -F ref=$CI_COMMIT_BRANCH https://gitlab.com/api/v4/projects/21908959/trigger/pipeline"

release:
  image: node:13
  stage: release
  only:
    - master
  script:
    - ls .
    - bash tag.sh