[tool.flakehell]
baseline = ".flakehell_baseline"
format = "grouped"
show_source = true
statistics = false
doctests = true
enable_extensions = "G"

accept_encodings = "utf-8"
max_complexity = 6
max_line_length = 80

ignore = "D100, D104, D401, W504, RST303, RST304, DAR103, DAR203"

[tool.flakehell.plugins]
"flake8-*" = ["+*"]
mccabe = ["+*"]
nitpick = ["+*"]
"pep8-naming" = ["+*"]
pycodestyle = ["+*"]
# pyflakes = ["+*"]
"wemake-python-styleguide" = ["+*"]
