HANA3D_NAME: hana3d_local
HANA3D_UI: hana3d_local_ui
HANA3D_ASSET: hana3d_local_asset
HANA3D_MODELS: hana3d_local_models
HANA3D_SCENES: hana3d_local_scenes
HANA3D_MATERIALS: hana3d_local_materials
HANA3D_PROFILE: hana3d_local_profile
HANA3D_DESCRIPTION: Hana3D (local)
HANA3D_AUTH_URL: https://hana3d.us.auth0.com
HANA3D_AUTH_CLIENT_ID: K3Tp6c6bbvF8gT6nwK1buVZjpTeDeXfu
HANA3D_AUTH_AUDIENCE: https://staging-hana3d.com
HANA3D_PLATFORM_URL: https://dev.hana3d.com
HANA3D_AUTH_LANDING: /landing
HANA3D_URL: http://localhost:5000
HANA3D_LOG_LEVEL: DEBUG
