HANA3D_NAME: hana3d_production
HANA3D_MODELS: hana3d_production_models
HANA3D_SCENES: hana3d_production_scenes
HANA3D_MATERIALS: hana3d_production_materials
HANA3D_PROFILE: hana3d_production_profile
HANA3D_DESCRIPTION: Hana3D
HANA3D_AUTH_URL: https://hana3d.us.auth0.com
HANA3D_AUTH_CLIENT_ID: DDfs3mFwivtSoUOqwCZnJODaOhmwZvor
HANA3D_AUTH_AUDIENCE: https://hana3d.com
HANA3D_PLATFORM_URL: https://hana3d.com
HANA3D_AUTH_LANDING: /landing
HANA3D_URL: https://api.hana3d.com