name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - run: pip install -r requirements.txt
      - run: make lint
        env:
          STAGE: dev
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - run: scripts/tests/install-blender
        env:
          BLENDER_VERSION: "2.91"
      - run: scripts/tests/install-addon
        env:
          BLENDER_VERSION: "2.91"
          STAGE: dev
      - run: make install-test
        env:
          STAGE: dev
      - run: make unit-test
        env:
          STAGE: dev

  e2e:
    name: Run E2E tests
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.2.0
        with:
          owner: hana3d
          repo: e2e-tests
          github_token: ${{ secrets.HANA3D_BOT_ACCESS_TOKEN }}
          event_type: dev
          workflow_file_name: webhook.yml
